#!/bin/sh

# Source System Configuration Files
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set Look and Feel
[ -f $HOME/.Xresources ] && xrdb -merge $HOME/.Xresources

# Split Widescreen Monitor
xrandr --setmonitor iiyama-left  "1720/400x1440/345+2560+0" HDMI-A-0
xrandr --setmonitor iiyama-right "1720/400x1440/345+4280+0" none

# Keyring
eval $( /usr/bin/gnome-keyring-daemon --start )
export SSH_AUTH_SOCK

# Run the Environment
numlockx &
unclutter --timeout 2 --jitter 10 --ignore-scrolling &
feh --no-fehbg --bg-fill ~/.config/feh/current
nextcloud &
dunst &

# Allow X11 Access to other users
xhost +si:localuser:kirchenweb

# Create i3 config from config-parts
generate-i3-config.sh

# Run i3
exec /usr/bin/i3
