#!/bin/sh

SCRIPTDIR="$( cd -P -- "$( dirname -- "${0}" )" && pwd )"
SOURCEDIR="${SCRIPTDIR}/xinitrc.d"

# Source Configuration Files
if [ -d "${SOURCEDIR}" ] ; then
 for f in "${SOURCEDIR}/"*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
