# Monitors
workspace $ws1 output DisplayPort-0
workspace $ws4 output DisplayPort-0
workspace $ws7 output DisplayPort-0
workspace $ws2 output iiyama-left
workspace $ws5 output iiyama-left
workspace $ws8 output iiyama-left
workspace $ws3 output iiyama-right
workspace $ws6 output iiyama-right
workspace $ws9 output iiyama-right
